In [4]:
import pandas as pd

df = pd.read_csv('reuters_headlines.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'reuters_headlines.csv'

In [12]:
df

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...
...,...,...,...
32765,Malaysia says never hired British data firm at...,Mar 20 2018,The Malaysian government and the ruling party ...
32766,Prosecutors search Volkswagen headquarters in ...,Mar 20 2018,German prosecutors said on Tuesday they had se...
32767,McDonald's sets greenhouse gas reduction targets,Mar 20 2018,McDonald's Corp on Tuesday announced an approv...
32768,Pratt & Whitney to deliver spare A320neo engin...,Mar 20 2018,Pratt & Whitney will soon begin deliveries of ...
32769,UK will always consider ways to improve data l...,Mar 20 2018,Britain will consider any suggestions to give ...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32770 entries, 0 to 32769
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Headlines    32770 non-null  object
 1   Time         32770 non-null  object
 2   Description  32770 non-null  object
dtypes: object(3)
memory usage: 768.2+ KB

In [14]:
df['Time'] = pd.to_datetime(df['Time'], format='%b %d %Y', errors='raise')

In [15]:
df = df.sort_values(by='Time')

In [16]:
df

,Headlines,Time,Description
32769,UK will always consider ways to improve data l...,2018-03-20,Britain will consider any suggestions to give ...
32738,Senate Democrat wants Facebook CEO Zuckerberg ...,2018-03-20,"U.S. Senator Dianne Feinstein, the top Democra..."
32737,"Factbox: How United States, others regulate au...",2018-03-20,An Uber self-driving sport utility vehicle str...
32736,Cambridge Analytica played key Trump campaign ...,2018-03-20,The suspended chief executive of UK-based poli...
32735,Start of AT&T-Time Warner trial delayed until ...,2018-03-20,Opening statements in the trial to decide if A...
...,...,...,...
39,Exclusive: Pact to aid poor cocoa farmers in p...,2020-07-17,The steepest dive in cocoa demand in a decade ...
3,Twitter says attackers downloaded data from up...,2020-07-18,Twitter Inc said on Saturday that hackers were...
2,Trail of missing Wirecard executive leads to B...,2020-07-18,Former Wirecard chief operating officer Jan M...
1,Disney cuts ad spending on Facebook amid growi...,2020-07-18,Walt Disney has become the latest company to ...
0,TikTok considers London and other locations fo...,2020-07-18,TikTok has been in discussions with the UK gov...

In [17]:
df.reset_index()

,index,Headlines,Time,Description
0,32769,UK will always consider ways to improve data l...,2018-03-20,Britain will consider any suggestions to give ...
1,32738,Senate Democrat wants Facebook CEO Zuckerberg ...,2018-03-20,"U.S. Senator Dianne Feinstein, the top Democra..."
2,32737,"Factbox: How United States, others regulate au...",2018-03-20,An Uber self-driving sport utility vehicle str...
3,32736,Cambridge Analytica played key Trump campaign ...,2018-03-20,The suspended chief executive of UK-based poli...
4,32735,Start of AT&T-Time Warner trial delayed until ...,2018-03-20,Opening statements in the trial to decide if A...
...,...,...,...,...
32765,39,Exclusive: Pact to aid poor cocoa farmers in p...,2020-07-17,The steepest dive in cocoa demand in a decade ...
32766,3,Twitter says attackers downloaded data from up...,2020-07-18,Twitter Inc said on Saturday that hackers were...
32767,2,Trail of missing Wirecard executive leads to B...,2020-07-18,Former Wirecard chief operating officer Jan M...
32768,1,Disney cuts ad spending on Facebook amid growi...,2020-07-18,Walt Disney has become the latest company to ...
32769,0,TikTok considers London and other locations fo...,2020-07-18,TikTok has been in discussions with the UK gov...

In [18]:
df.to_csv('reuters_headlines_input.csv',index=False)

In [5]:
df = pd.read_csv('reuters.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 157: invalid start byte